---
- name: Gather facts
  include_role:
    name: tvartom.gather_facts
    tasks_from: gather_facts
  vars:
    facts_options:
      var_files: [] # Read variables from files in var/[item].yml
      #  - system
      #  - webinstances
      #  - users
      host_vars_from_host: true
      diskspace_message: false

- include_role:
    name: tvartom.basic_centos_tools
- include_role:
    name: tvartom.users
- include_role:
    name: basic_centos_tools
- include_role:
    name: mariadb
- include_role:
    name: git
- include_role:
    name: google_cloud_sdk
- include_role:
    name: serveradmin
